# Generated by Django 4.1.5 on 2023-01-31 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='picture',
            field=models.ImageField(default='/pictures/empty.png', upload_to='pictures'),
        ),
    ]
