# Generated by Django 4.1.5 on 2023-01-31 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsite', '0002_person_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=models.ImageField(default='/pictures/circleempty.png', upload_to='pictures'),
        ),
    ]
